# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f4ba1947e1fd5e148b8b18221c1e7f68b3e16e6a0952537b188c7e60459b796cf77c425f71932ae3f168793b49c4bc50c25f5f04261ef583fe81f2a55ef65a7d

test:
  secret_key_base: 5178620c1da45d53d7bf15940e8b2eb55c0cf413fd0ab3dd0e5f3b03c086ba82364955b942bc42cbfc19b73251d7703ea9b425de1286d8a4f48c3066ab3304f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
